[workspace]
resolver = "2"
members = [
    "noshtastic-app",
    "noshtastic-link",
    "noshtastic-sync",
    "noshtastic-testgw",
]

[workspace.dependencies]
# local dependencies
noshtastic-link = { path = "./noshtastic-link" }
noshtastic-sync = { path = "./noshtastic-sync" }
noshtastic-testgw = { path = "./noshtastic-testgw" }

# common dependencies
anyhow = "1.0"
async-trait = "0.1.83"
env_logger = "0.11"
hex = "0.4"
log = "0.4"
nostrdb = { git = "https://github.com/damus-io/nostrdb-rs", rev = "2111948b078b24a1659d0bd5d8570f370269c99b" }
#nostrdb = "0.5"
prost = "0.11"
thiserror = "2.0"
tokio = { version = "1.42", features = ["full"] }
tonic = "0.8"
