[workspace]
resolver = "2"
package.version = "0.1.0"
members = [
    "crates/noshtastic-cli",
    "crates/noshtastic-link",
    "crates/noshtastic-sync",
    "crates/noshtastic-testgw",
]

[workspace.dependencies]
# local dependencies
noshtastic-link = { path = "./crates/noshtastic-link" }
noshtastic-sync = { path = "./crates/noshtastic-sync" }
noshtastic-testgw = { path = "./crates/noshtastic-testgw" }

# common dependencies
anyhow = "1.0"
async-trait = "0.1.83"
env_logger = "0.11"
hex = "0.4"
log = "0.4"
nostrdb = { git = "https://github.com/damus-io/nostrdb-rs", rev = "df03575b0a0133d8700e90d538c01d253f4a480a" }
#nostrdb = "0.5"
prost = "0.11"
thiserror = "2.0"
tokio = { version = "1.42", features = ["full"] }
tonic = "0.8"
