[workspace]
resolver = "2"
members = [
    "noshtastic-app",
    "noshtastic-link",
    "noshtastic-sync",
]

[workspace.dependencies]
noshtastic-link = { path = "./noshtastic-link" }
noshtastic-sync = { path = "./noshtastic-sync" }

# common dependencies
async-trait = "0.1.83"
log = "0.4"
prost = "0.11"
thiserror = "2.0"
tokio = { version = "1.42", features = ["full"] }
tonic = "0.8"
