[package]
name = "noshtastic-link"
description = "A library which facilitates sending noshtastic messages to meshtastic radios."
version = { workspace = true }
authors = ["Ken Sedgwick <ken@bonsai.com>"]
edition = "2021"

[dependencies]
# common dependencies
async-trait = { workspace = true }
hex = { workspace = true }
log = { workspace = true }
prost = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }

# unique dependencies
sha2 = "0.10"
tokio-serial = "5.4"
meshtastic = "0.1"

[build-dependencies]
tonic-build = "0.8"

[lib]
crate-type = ["lib", "cdylib"]
